Game.Economy = {
  wages: {
    none: 0,
    barista: 14,
    office: 22,
    trainDriver: 40,
    retailAssistant: 16,
    factoryWorker: 24,
    hospitalPorter: 26,
    farmHand: 15,
    foodCourier: 15,
    callCenterRep: 18,
    salesAssociate: 21,
    itSupport: 28,
    warehousePicker: 17,
    forkliftOperator: 23,
    welderApprentice: 26,
    qualityInspector: 30,
    clinicReceptionist: 20,
    phlebotomist: 30,
    emt: 34,
    labTechnician: 36,
    dairyWorker: 15,
    tourGuide: 17,
    groundskeeper: 19,
    greenhouseTech: 24,

    // Advanced jobs
    accountingClerk: 36,
    financialAnalyst: 60,
    corporateDirector: 95,
    dataAnalyst: 52,
    softwareDeveloper: 62,
    maintenanceTechnician: 42,
    processEngineer: 70,
    qualityEngineer: 58,
    automationEngineer: 66,
    railOperationsChief: 88,
    medicalAssistant: 44,
    registeredNurse: 72,
    radiologyTech: 64,
    equipmentOperator: 32,
    agriManager: 50,
    sustainabilityConsultant: 82,
    agronomist: 54
  },
  schoolCosts: {
    nightClass: 60,
    engineering: 220,
    business: 180
  },
  doctorVisit: 80,
  hospitalStay: 320,
  travelBaseCost: 15,
  propertyTaxRatePerDay: 0.0002
};
